import type { PortfolioData } from '@/types';

export const defaultPortfolioData: PortfolioData = {
  educations: [
    {
      id: 'e1',
      institution: 'AMA Computer College',
      degree: 'Bachelor of Science',
      field_of_study: 'Information Technology',
      start_year: '2014',
      end_year: '2018',
      is_current: false,
      order_index: 0,
      created_at: new Date().toISOString(),
    },
  ],
  profile: {
    id: 'default',
    user_id: 'default',
    name: 'Denis Hain',
    title: 'Full Stack Developer',
    bio: 'Passionate Full Stack Developer with 7+ years of experience building scalable web and mobile applications. Specialized in React/Next.js and Laravel ecosystems, with a strong foundation in both frontend and backend development. Led development of enterprise systems for NYK-Fil Maritime E-Training, Inc., delivering solutions that streamline operations across web and mobile platforms.',
    phone: '+(63) 950 909 5677',
    email: 'denishain@gmail.com',
    github: 'https://github.com/MysticMaccc',
    portfolio_url: 'https://sfr-portfolio-2026.vercel.app',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  experiences: [
    {
      id: '1',
      company: 'NYK-FIL Maritime E-Training, Inc.',
      role: 'Senior Developer',
      start_date: '2021',
      end_date: '2025',
      is_current: false,
      description: [
        'Led development of enterprise-level web and mobile applications',
        'Architected and built Online Enrollment System and Mobile App',
        'Developed SpoonPH Fitness App (web + Android/iOS)',
        'Managed project planning, timelines, and resource allocation',
        'Conducted code reviews and mentored junior developers',
        'Implemented API development and authentication systems',
      ],
      order_index: 0,
      created_at: new Date().toISOString(),
    },
    {
      id: '2',
      company: 'NYK-FIL Maritime E-Training, Inc.',
      role: 'Junior Developer',
      start_date: '2018',
      end_date: '2021',
      is_current: false,
      description: [
        'Developed and maintained internal web applications',
        'Built Meal Tracker, Library, and Telephone Directory systems',
        'Created Procurement and Inventory management systems',
        'Developed Work Order Monitoring and Payroll systems',
        'Worked with Laravel framework and MySQL databases',
      ],
      order_index: 1,
      created_at: new Date().toISOString(),
    },
  ],
  projects: [
    {
      id: '1',
      title: 'Online Enrollment System',
      description: 'Full-featured online enrollment platform with admin dashboard, student portal, and real-time reporting for maritime training programs.',
      tech_stack: ['Laravel', 'React', 'MySQL', 'Tailwind CSS'],
      category: 'web',
      featured: true,
      order_index: 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Online Enrollment Android & iOS App',
      description: 'Cross-platform mobile application for the enrollment system, built with React Native and Capacitor JS.',
      tech_stack: ['React', 'Next.js', 'Capacitor JS', 'Tailwind CSS'],
      category: 'mobile',
      featured: true,
      order_index: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'SpoonPH Fitness App',
      description: 'Nutrition and fitness tracking web application with meal planning, calorie tracking, and progress monitoring features.',
      tech_stack: ['Laravel', 'Vue.js', 'MySQL', 'Bootstrap CSS'],
      category: 'web',
      featured: true,
      order_index: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'SpoonPH Fitness Android & iOS App',
      description: 'Mobile version of the SpoonPH fitness application with native features and offline support.',
      tech_stack: ['React', 'Capacitor JS', 'Tailwind CSS'],
      category: 'mobile',
      featured: false,
      order_index: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Procurement System',
      description: 'End-to-end procurement management system with purchase orders, vendor management, and approval workflows.',
      tech_stack: ['Laravel', 'Livewire', 'Alpine.js', 'Tailwind CSS'],
      category: 'web',
      featured: false,
      order_index: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '6',
      title: 'Inventory System',
      description: 'Comprehensive inventory management system with stock tracking, barcode support, and automated reorder alerts.',
      tech_stack: ['Laravel', 'MySQL', 'Bootstrap CSS', 'JavaScript'],
      category: 'web',
      featured: false,
      order_index: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '7',
      title: 'NYK Lecturer Payroll System',
      description: 'Automated payroll processing system for lecturers with attendance tracking, tax computation, and payslip generation.',
      tech_stack: ['Laravel', 'MySQL', 'Blade', 'Bootstrap CSS'],
      category: 'web',
      featured: false,
      order_index: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '8',
      title: 'Work Order Monitoring System',
      description: 'Real-time work order tracking and management system with status updates, assignments, and reporting dashboard.',
      tech_stack: ['Laravel', 'Livewire', 'MySQL', 'Tailwind CSS'],
      category: 'web',
      featured: false,
      order_index: 7,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '9',
      title: 'Library System',
      description: 'Digital library management system with book cataloging, member management, and borrowing/return tracking.',
      tech_stack: ['Laravel', 'MySQL', 'Bootstrap CSS', 'jQuery'],
      category: 'web',
      featured: false,
      order_index: 8,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '10',
      title: 'Meal Tracker System',
      description: 'Cafeteria meal tracking system with daily menu management, consumption logging, and nutritional reporting.',
      tech_stack: ['Laravel', 'MySQL', 'Blade', 'CSS'],
      category: 'web',
      featured: false,
      order_index: 9,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: '11',
      title: 'Telephone Directory System',
      description: 'Internal telephone directory with department search, contact management, and quick-dial features.',
      tech_stack: ['Laravel', 'MySQL', 'Bootstrap CSS'],
      category: 'web',
      featured: false,
      order_index: 10,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  skills: [
    // Full Stack
    { id: 's1', category: 'Full Stack', name: 'React (Next.js) + Laravel', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's2', category: 'Full Stack', name: 'TALL Stack (Tailwind, Alpine, Laravel, Livewire)', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    // Frontend
    { id: 's3', category: 'Frontend', name: 'React JS', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's4', category: 'Frontend', name: 'TypeScript', level: 'intermediate', order_index: 1, created_at: new Date().toISOString() },
    { id: 's5', category: 'Frontend', name: 'Next.js', level: 'advanced', order_index: 2, created_at: new Date().toISOString() },
    { id: 's6', category: 'Frontend', name: 'Laravel Livewire', level: 'advanced', order_index: 3, created_at: new Date().toISOString() },
    { id: 's7', category: 'Frontend', name: 'Alpine.js', level: 'intermediate', order_index: 4, created_at: new Date().toISOString() },
    // Backend
    { id: 's8', category: 'Backend', name: 'Laravel Framework', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's9', category: 'Backend', name: 'REST API Development', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    { id: 's10', category: 'Backend', name: 'API Authentication & Authorization', level: 'advanced', order_index: 2, created_at: new Date().toISOString() },
    // Fundamentals
    { id: 's11', category: 'Fundamentals', name: 'HTML', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's12', category: 'Fundamentals', name: 'CSS', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    { id: 's13', category: 'Fundamentals', name: 'JavaScript', level: 'advanced', order_index: 2, created_at: new Date().toISOString() },
    { id: 's14', category: 'Fundamentals', name: 'PHP', level: 'advanced', order_index: 3, created_at: new Date().toISOString() },
    // CSS Frameworks
    { id: 's15', category: 'CSS Frameworks', name: 'Tailwind CSS', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's16', category: 'CSS Frameworks', name: 'Bootstrap CSS', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    // Database
    { id: 's17', category: 'Database', name: 'MySQL', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's18', category: 'Database', name: 'Supabase (PostgreSQL)', level: 'intermediate', order_index: 1, created_at: new Date().toISOString() },
    // Cloud & Hosting
    { id: 's19', category: 'Cloud & Hosting', name: 'Vercel', level: 'intermediate', order_index: 0, created_at: new Date().toISOString() },
    { id: 's20', category: 'Cloud & Hosting', name: 'Hostinger', level: 'intermediate', order_index: 1, created_at: new Date().toISOString() },
    { id: 's21', category: 'Cloud & Hosting', name: 'GoDaddy', level: 'intermediate', order_index: 2, created_at: new Date().toISOString() },
    // Version Control
    { id: 's22', category: 'Version Control', name: 'Git', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's23', category: 'Version Control', name: 'GitHub', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    // Package Managers
    { id: 's24', category: 'Package Managers', name: 'Composer', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's25', category: 'Package Managers', name: 'npm', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    { id: 's26', category: 'Package Managers', name: 'Yarn', level: 'intermediate', order_index: 2, created_at: new Date().toISOString() },
    // Mobile
    { id: 's27', category: 'Mobile', name: 'React Native (Capacitor JS)', level: 'intermediate', order_index: 0, created_at: new Date().toISOString() },
    { id: 's28', category: 'Mobile', name: 'Android App Development', level: 'intermediate', order_index: 1, created_at: new Date().toISOString() },
    { id: 's29', category: 'Mobile', name: 'iOS App Development', level: 'intermediate', order_index: 2, created_at: new Date().toISOString() },
    // Methodologies
    { id: 's30', category: 'Methodologies', name: 'Object Oriented Programming', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's31', category: 'Methodologies', name: 'Model-View-Controller (MVC)', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    { id: 's32', category: 'Methodologies', name: 'Test Driven Development (TDD)', level: 'intermediate', order_index: 2, created_at: new Date().toISOString() },
    { id: 's33', category: 'Methodologies', name: 'Scrum / Agile', level: 'advanced', order_index: 3, created_at: new Date().toISOString() },
    // Project Management
    { id: 's34', category: 'Project Management', name: 'Project Planning & Scheduling', level: 'advanced', order_index: 0, created_at: new Date().toISOString() },
    { id: 's35', category: 'Project Management', name: 'Scope Management', level: 'advanced', order_index: 1, created_at: new Date().toISOString() },
    { id: 's36', category: 'Project Management', name: 'Scrum Facilitation & Sprint Management', level: 'advanced', order_index: 2, created_at: new Date().toISOString() },
    { id: 's37', category: 'Project Management', name: 'Technical Specification Drafting', level: 'advanced', order_index: 3, created_at: new Date().toISOString() },
    { id: 's38', category: 'Project Management', name: 'Notion', level: 'intermediate', order_index: 4, created_at: new Date().toISOString() },
  ],
  trainings: [
    { id: 't1', title: 'SCRUM Master Certified Training', provider: 'APEX Global', year: '2023', order_index: 0, created_at: new Date().toISOString() },
    { id: 't2', title: 'Basic iOS Mobile Application Development', provider: 'FIT Academy', year: '2022', order_index: 1, created_at: new Date().toISOString() },
    { id: 't3', title: 'Advance Android Application Development', provider: 'FIT Academy', year: '2021', order_index: 2, created_at: new Date().toISOString() },
    { id: 't4', title: 'Basic Android Application Development', provider: 'FIT Academy', year: '2020', order_index: 3, created_at: new Date().toISOString() },
    { id: 't5', title: 'Laravel Framework', provider: 'Inventive Media', year: '2019', order_index: 4, created_at: new Date().toISOString() },
    { id: 't6', title: 'Laravel + Vue JS', provider: 'Udemy', year: '2021', order_index: 5, created_at: new Date().toISOString() },
    { id: 't7', title: 'Chat GPT Master Course', provider: 'Udemy', year: '2023', order_index: 6, created_at: new Date().toISOString() },
    { id: 't8', title: 'WordPress Development', provider: 'Udemy', year: '2020', order_index: 7, created_at: new Date().toISOString() },
    { id: 't9', title: 'Bootstrap CSS Framework', provider: 'Udemy', year: '2019', order_index: 8, created_at: new Date().toISOString() },
    { id: 't10', title: 'Advanced CSS & Sass', provider: 'Udemy', year: '2019', order_index: 9, created_at: new Date().toISOString() },
  ],
};
